# Generated by Django 3.2.8 on 2021-10-28 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list_appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('doctor', 'Doctor'), ('paciente', 'Paciente')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Roles User',
                'verbose_name_plural': 'Roles User',
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
