# Generated by Django 3.2.8 on 2021-10-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_appointments', '0003_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
