# Generated by Django 3.2.8 on 2021-11-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_appointments', '0004_delete_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_provider', models.SmallIntegerField()),
                ('id_section', models.CharField(max_length=100)),
            ],
        ),
    ]
